# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false
  # Render `lineNos=true` as inline line numbers. The table layout Chroma
  # produces leaves no gap between numbers and code.
  lineNumbersInTable = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
