# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "espressif"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

mainSections = ["blog"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false

# defaultBackgroundImage = "/img/ocean.jpg"
# defaultFeaturedImage = "/img/ocean.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[giscus]
  giscusDisableComments = false
  giscusDataRepo = "espressif/developer-portal"
  giscusDataRepoID = "R_kgDOLPlldw"
  giscusDataCategory = "General"
  giscusDataCategoryID = "DIC_kwDOLPlld84CdKDO"

[header]
  layout = "fixed-fill" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, hero, card, background, custom
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "blog"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = true
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  editURL = "https://github.com/espressif/developer-portal/tree/main/content"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = false
  sharingLinks = [ "linkedin", "twitter", "reddit", "whatsapp", "telegram", "facebook", "email"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showViews = true
  showLikes = true
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = true
  showLikes = true
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[firebase]
  apiKey = ""
  authDomain = ""
  projectId = ""
  storageBucket = ""
  messagingSenderId = ""
  appId = ""
  measurementId = ""

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
