# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

baseURL = "https://developer.espressif.com/"
title = "Espressif Developer Portal"

buildDrafts = false
buildFuture = false

[services]
  [services.googleAnalytics]
    id = "G-K9NTMXPGN3"
