# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

baseURL = "https://developer.espressif.com/"
title = "Espressif Developer Portal"

buildDrafts = false
buildFuture = false

[deployment]
  [[deployment.targets]]
    name = 'production'
    url = 's3://kirill-devportal?region=ap-east-1'
    exclude = "persist/**"

[services]
  [services.googleAnalytics]
    id = "G-K9NTMXPGN3"
