name: Cron job to redeploy Hugo site daily

on:
  schedule:
    - cron: '5 0 * * *'
  # Allow manual runs from the Actions tab
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN
permissions:
  contents: read
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    if: github.repository_owner == 'espressif'
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo
        run: bash tools/ci/install-hugo.sh

      - name: Build website with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify

      - name: Deploy prod with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: hugo deploy --target=production

  invalidate-cache:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          PATHS: "/*"
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
