name: Build preview for PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

env:
  HUGO_BASEURL: "https://preview-developer.espressif.com/"

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hugo CLI
        env:
          HUGO_VERSION: 0.135.0
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build website with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: preview
          HUGO_ENV: preview
        run: |
          hugo \
            --baseURL "${{ env.HUGO_BASEURL }}pr${{ github.event.pull_request.number }}/" \
            --gc \
            --minify

      - name: Print preview link to PR
        run: |
          echo "Preview link ${{ env.HUGO_BASEURL }}pr${{ github.event.pull_request.number }}/"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public-folder
          path: ./public

      - name: Publish index.xml
        if: success()
        run: |
          if [ -f ./public/index.xml ]; then
            echo "Contents of index.xml:"
            cat ./public/index.xml
          else
            echo "index.xml not found in ./public"
          fi

      - name: Create PR number file
        run: echo "${{ github.event.pull_request.number }}" > pr-num.txt

      - name: Upload PR number artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-num
          path: pr-num.txt
