name: Check links in diffs

on:
  pull_request:
    branches: [main]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Create baseline branch by reverting feature branch changes
        run: |
          # Create a copy of the feature branch
          git checkout -b baseline-copy

          # git checkout ${{ github.event.pull_request.head.sha }}

          # Find the base commit where the feature branch diverged from main
          base_commit=$(git merge-base origin/main baseline-copy)

          # Reset the new branch to the base commit
          git reset --hard $base_commit

      - name: Dump all links from baseline-copy
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: |
            --dump
            --include-fragments
            --exclude-path ./themes/
            --exclude-path ./layouts/
            .
          output: ./links-baseline.txt

      - name: Print links-baseline.txt
        run: cat links-baseline.txt

      - name: Stash untracked files
        run: git stash push --include-untracked

      - name: Check out feature branch
        run: git checkout ${{ github.head_ref }}

      - name: Apply stashed changes
        # Apply stashed changes, ignore errors if stash is empty
        run: git stash pop || true

      - name: Append links-baseline.txt to .lycheeignore
        run: cat links-baseline.txt >> .lycheeignore

      - name: Check .lycheeignore content
        run: cat .lycheeignore

      - name: Check links
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: |
            --no-progress
            --include-fragments
            --exclude-path ./themes/
            --exclude-path ./layouts/
            .
          fail: true  # Fail action if broken links are found

      - name: Suggestions
        if: failure()
        run: |
          echo -e "\nPlease review the links reported in the Check links step above."
          echo -e "If a link is valid but fails due to a CAPTCHA challenge, IP blocking, login requirements, etc.,"
          echo -e "consider adding such links to the .lycheeignore file to bypass future checks.\n"
          exit 1
