name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          reporter: github-pr-check
          vale_flags: "--minAlertLevel=suggestion"
          fail_on_error: true
